
CREATE TABLE IF NOT EXISTS player (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    points INT NOT NULL DEFAULT 0,
    count INT NOT NULL DEFAULT 0,
    network VARCHAR(255) NOT NULL
)